# https://taskfile.dev

version: '3'

tasks:
  gen:
    cmds:
      - >
        protoc -I proto proto/database/database.proto
        --go_out=./gen/go/ --go_opt=paths=source_relative
        --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
    silent: true
